### ISSUE TITLE
Upstream was renamed to locustio

### ISSUE THREAD

**Issue by nrbgt** [conda-forge/locust-feedstock#1]
Issue:
It appears the upstream pypi package was renamed to `locustio`:

https://pypi.org/project/locustio/#history

Will PR applying the name in-place, but a new feedstock might be more appropriate?

**Comment by scopatz** [comment]
Name in-place is less hassle than a new feedtsock

**Comment by carlodri** [comment]
@scopatz but then users get confused due to different feedstock name and package name (I don't like that personally). I would rather leave this repo here, for possible back-release and service requests, and make a new repo for `locustio`. What do you think? Maybe I'm a little OCD here... 🙄
